apiVersion: apps/v1
kind: Deployment
metadata:
  name: Notice
  labels:
    app: Notice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Notice
  template:
    metadata:
      labels:
        app: Notice
    spec:
      containers:
        - name: Notice
          image: username/Notice:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
